version: '3.4'
services:
  netbox:
    ports:
    - 8888:8080
    healthcheck:
      start_period: 180s
    environment:
      SKIP_SUPERUSER: "false"
      # SUPERUSER_API_TOKEN: ""
      SUPERUSER_EMAIL: "here@there.com"
      SUPERUSER_NAME: "admin"
      SUPERUSER_PASSWORD: "admin"
    restart: unless-stopped
  netbox-worker:
    restart: unless-stopped
  netbox-housekeeping:
    restart: unless-stopped
  postgres:
    restart: unless-stopped
  redis:
    restart: unless-stopped
  redis-cache:
    restart: unless-stopped
